In [58]:
import numpy as np 
import pandas as pd
import ast

In [102]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [103]:

movies = movies.merge(credits, on='title')

In [104]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [105]:
#un columns ko hatado jo nhi chhaie
#or jo chahiye wo laga do
movies = movies[['movie_id','title','keywords','overview','genres','cast','crew']]

In [106]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   keywords  4809 non-null   object
 3   overview  4806 non-null   object
 4   genres    4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [107]:
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

movies.isnull().sum()

In [108]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
overview    3
genres      0
cast        0
crew        0
dtype: int64

In [109]:
movies.dropna(inplace=True)

In [110]:
movies.duplicated().sum()

0

In [111]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [112]:
#create helper functiona
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
   
        L.append(i['name'])
        return L

In [113]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",[Action],"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",[Adventure],"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,[Action],"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,[Action],"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",[Action],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [114]:
movies['cast'] = movies['cast'].apply(convert)

In [115]:
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",[Action],[Sam Worthington],"[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",[Adventure],[Johnny Depp],"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,[Action],[Daniel Craig],"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,[Action],[Christian Bale],"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",[Action],[Taylor Kitsch],"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [116]:
movies['keywords']=movies['keywords'].apply(convert)

In [117]:
movies['cast'][0]

['Sam Worthington']

In [118]:
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
        return L

In [119]:
movies['cast']=movies['cast'].apply(convert3)

ValueError: malformed node or string: ['Sam Worthington']

In [120]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [121]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
            L.append(i['name'])
            break
    return L

In [122]:
movies['crew']=movies['crew'].apply(fetch_director)

In [123]:
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,[culture clash],"In the 22nd century, a paraplegic Marine is di...",[Action],[Sam Worthington],[James Cameron]
1,285,Pirates of the Caribbean: At World's End,[ocean],"Captain Barbossa, long believed to be dead, ha...",[Adventure],[Johnny Depp],[Gore Verbinski]
2,206647,Spectre,[spy],A cryptic message from Bond’s past sends him o...,[Action],[Daniel Craig],[Sam Mendes]
3,49026,The Dark Knight Rises,[dc comics],Following the death of District Attorney Harve...,[Action],[Christian Bale],[Christopher Nolan]
4,49529,John Carter,[based on novel],"John Carter is a war-weary, former military ca...",[Action],[Taylor Kitsch],[Andrew Stanton]

In [124]:
movies['genres']

0            [Action]
1         [Adventure]
2            [Action]
3            [Action]
4            [Action]
            ...
4804         [Action]
4805         [Comedy]
4806         [Comedy]
4807             None
4808    [Documentary]
Name: genres, Length: 4806, dtype: object

In [125]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [126]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

TypeError: 'NoneType' object is not iterable

In [128]:
movies['overview'][10]

'Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest too felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.'

In [129]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [130]:
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,[culture clash],"In the 22nd century, a paraplegic Marine is di...",[Action],[Sam Worthington],[James Cameron]
1,285,Pirates of the Caribbean: At World's End,[ocean],"Captain Barbossa, long believed to be dead, ha...",[Adventure],[Johnny Depp],[Gore Verbinski]
2,206647,Spectre,[spy],A cryptic message from Bond’s past sends him o...,[Action],[Daniel Craig],[Sam Mendes]
3,49026,The Dark Knight Rises,[dc comics],Following the death of District Attorney Harve...,[Action],[Christian Bale],[Christopher Nolan]
4,49529,John Carter,[based on novel],"John Carter is a war-weary, former military ca...",[Action],[Taylor Kitsch],[Andrew Stanton]

In [131]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [132]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [133]:
import ast

def collapse(L):
    result = []
    try:
        # If L is a stringified list, convert it
        if isinstance(L, str):
            L = ast.literal_eval(L)
        # If it's not iterable, skip
        if not isinstance(L, list):
            return result
        for i in L:
            # If each element is a dict with a 'name' key
            if isinstance(i, dict) and 'name' in i:
                result.append(i['name'].replace(" ", ""))
            # If each element is a string (optional case)
            elif isinstance(i, str):
                result.append(i.replace(" ", ""))
    except Exception as e:
        print(f"Error: {e} → {L}")
    return result

In [134]:
movies['cast'] = movies['cast'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [135]:
movies['cast'].head(3)

0    [SamWorthington]
1        [JohnnyDepp]
2       [DanielCraig]
Name: cast, dtype: object

In [136]:
movies.head()

,movie_id,title,keywords,overview,genres,cast,crew
0,19995,Avatar,[cultureclash],"[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[SamWorthington],[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,[ocean],"[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[JohnnyDepp],[GoreVerbinski]
2,206647,Spectre,[spy],"[A, cryptic, message, from, Bond’s, past, send...",[Action],[DanielCraig],[SamMendes]
3,49026,The Dark Knight Rises,[dccomics],"[Following, the, death, of, District, Attorney...",[Action],[ChristianBale],[ChristopherNolan]
4,49529,John Carter,[basedonnovel],"[John, Carter, is, a, war-weary,, former, mili...",[Action],[TaylorKitsch],[AndrewStanton]

In [137]:
movies['tags'] = movies['overview'] +movies['genres'] + movies['keywords']+movies['cast'] + movies['crew']

In [147]:
new_df = movies[['movie_id','title','tags']]

In [148]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\patid\AppData\Local\Temp\ipykernel_6032\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [139]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [149]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [150]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash SamWorthington JamesCameron'

In [142]:
pip install nltk

Requirement already satisfied: nltk in c:\users\patid\100dayml\anaconda\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\patid\100dayml\anaconda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\patid\100dayml\anaconda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\patid\100dayml\anaconda\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\patid\appdata\roaming\python\python312\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\patid\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [152]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\patid\AppData\Local\Temp\ipykernel_6032\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [153]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [178]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [175]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [173]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words = 'english')

In [179]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [174]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [184]:
cv.get_feature_names_out(45)

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [183]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action cultureclash samworthington jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action cultureclash samworthington jamescameron'

In [186]:
new_df['tag']= new_df['tags'].apply(stem)

C:\Users\patid\AppData\Local\Temp\ipykernel_6032\1670047465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']= new_df['tags'].apply(stem)

In [185]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action cultureclash samworthington jamescameron'

In [182]:
ps.stem('danced')

'danc'

In [187]:
from sklearn.metrics.pairwise import cosine_similarity

In [192]:
similarity = cosine_similarity(vectors)

In [200]:
sorted(list(enumerate(similarity[0])),reverse= True)

[(4805, 0.0),
 (4804, 0.0),
 (4803, 0.0),
 (4802, 0.0),
 (4801, 0.04364357804719847),
 (4800, 0.0),
 (4799, 0.051639777949432225),
 (4798, 0.03450327796711771),
 (4797, 0.0),
 (4796, 0.0),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.0),
 (4792, 0.0),
 (4791, 0.0),
 (4790, 0.0),
 (4789, 0.0),
 (4788, 0.0),
 (4787, 0.0),
 (4786, 0.0),
 (4785, 0.0),
 (4784, 0.0),
 (4783, 0.0),
 (4782, 0.050636968354183326),
 (4781, 0.05270462766947299),
 (4780, 0.0),
 (4779, 0.0),
 (4778, 0.0),
 (4777, 0.0),
 (4776, 0.0),
 (4775, 0.0),
 (4774, 0.0),
 (4773, 0.0),
 (4772, 0.0408248290463863),
 (4771, 0.0),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.0),
 (4766, 0.0),
 (4765, 0.0),
 (4764, 0.0),
 (4763, 0.0),
 (4762, 0.0),
 (4761, 0.0),
 (4760, 0.0),
 (4759, 0.0),
 (4758, 0.0),
 (4757, 0.0816496580927726),
 (4756, 0.0),
 (4755, 0.0),
 (4754, 0.0),
 (4753, 0.0),
 (4752, 0.0),
 (4751, 0.0),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.0),
 (4747, 0.0),
 (4746, 0.0),
 (4745, 0.0),
 (4744, 0.0),
 (4743, 0.0),
 (4742, 0.0),
 (4741, 0.0),
 (4740, 0.0),
 (4739, 0.0),
 (4738, 0.0),
 (4737, 0.0),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.0),
 (4733, 0.0),
 (4732, 0.0),
 (4731, 0.0),
 (4730, 0.04134491152973615),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.0),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0),
 (4723, 0.0),
 (4722, 0.0),
 (4721, 0.0),
 (4720, 0.0),
 (4719, 0.0),
 (4718, 0.0),
 (4717, 0.0),
 (4716, 0.0),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.031544014893825585),
 (4710, 0.0),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.0),
 (4706, 0.0),
 (4705, 0.0),
 (4704, 0.06085806194501846),
 (4703, 0.0),
 (4702, 0.0),
 (4701, 0.0),
 (4700, 0.0),
 (4699, 0.0),
 (4698, 0.0),
 (4697, 0.0),
 (4696, 0.0),
 (4695, 0.0),
 (4694, 0.0),
 (4693, 0.0),
 (4692, 0.0),
 (4691, 0.0),
 (4690, 0.0),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.0),
 (4684, 0.0),
 (4683, 0.0),
 (4682, 0.02752409412815901),
 (4681, 0.0),
 (4680, 0.0),
 (4679, 0.0),
 (4678, 0.0),
 (4677, 0.0),
 (4676, 0.0),
 (4675, 0.0),
 (4674, 0.0),
 (4673, 0.0),
 (4672, 0.0),
 (4671, 0.0),
 (4670, 0.0),
 (4669, 0.0563436169819011),
 (4668, 0.0),
 (4667, 0.0),
 (4666, 0.0),
 (4665, 0.0),
 (4664, 0.0),
 (4663, 0.0),
 (4662, 0.0),
 (4661, 0.0),
 (4660, 0.0),
 (4659, 0.0),
 (4658, 0.0),
 (4657, 0.09274777915203365),
 (4656, 0.03450327796711771),
 (4655, 0.0),
 (4654, 0.0),
 (4653, 0.0),
 (4652, 0.05504818825631802),
 (4651, 0.0),
 (4650, 0.0),
 (4649, 0.0),
 (4648, 0.0),
 (4647, 0.0),
 (4646, 0.0),
 (4645, 0.0),
 (4644, 0.0),
 (4643, 0.0),
 (4642, 0.0),
 (4641, 0.0),
 (4640, 0.04879500364742665),
 (4639, 0.0),
 (4638, 0.0),
 (4637, 0.0),
 (4636, 0.09128709291752767),
 (4635, 0.0),
 (4634, 0.0),
 (4633, 0.0408248290463863),
 (4632, 0.059234887775909226),
 (4631, 0.0),
 (4630, 0.0),
 (4629, 0.0),
 (4628, 0.0),
 (4627, 0.0),
 (4626, 0.049690399499995326),
 (4625, 0.0),
 (4624, 0.04564354645876383),
 (4623, 0.06262242910851494),
 (4622, 0.0),
 (4621, 0.0),
 (4620, 0.04188539082916955),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.0),
 (4610, 0.0),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.0),
 (4606, 0.0),
 (4605, 0.0),
 (4604, 0.0),
 (4603, 0.0),
 (4602, 0.051639777949432225),
 (4601, 0.0),
 (4600, 0.0),
 (4599, 0.0),
 (4598, 0.0),
 (4597, 0.0),
 (4596, 0.0),
 (4595, 0.0),
 (4594, 0.06666666666666665),
 (4593, 0.0),
 (4592, 0.0),
 (4591, 0.0),
 (4590, 0.0),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.0),
 (4585, 0.0),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.0),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.0),
 (4578, 0.0),
 (4577, 0.0),
 (4576, 0.0),
 (4575, 0.0),
 (4574, 0.0),
 (4573, 0.0),
 (4572, 0.0),
 (4571, 0.0),
 (4570, 0.0),
 (4569, 0.04564354645876383),
 (4568, 0.06900655593423542),
 (4567, 0.0),
 (4566, 0.0),
 (4565, 0.023870495801314427),
 (4564, 0.06666666666666665),
 (4563, 0.0),
 (4562, 0.0),
 (4561, 0.0),
 (4560, 0.0),
 (4559, 0.0),
 (4558, 0.0),
 (4557, 0.06454972243679027),
 (4556, 0.0),
 (4555, 0.0),
 (4554, 0.0),
 (4553, 0.037267799624996496),
 (4552, 0.03806934938134405),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.04714045207910316),
 (4548, 0.0),
 (4547, 0.0),
 (4546, 0.0),
 (4545, 0.03688555567816587),
 (4544, 0.0),
 (4543, 0.0),
 (4542, 0.0),
 (4541, 0.0),
 (4540, 0.0),
 (4539, 0.0),
 (4538, 0.04244763599780088),
 (4537, 0.0),
 (4536, 0.0),
 (4535, 0.0),
 (4534, 0.0),
 (4533, 0.0),
 (4532, 0.0),
 (4531, 0.0),
 (4530, 0.0),
 (4529, 0.03806934938134405),
 (4528, 0.0),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.0),
 (4524, 0.0),
 (4523, 0.0),
 (4522, 0.0),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.050636968354183326),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.0),
 (4515, 0.0),
 (4514, 0.0),
 (4513, 0.0),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.0),
 (4509, 0.0),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.0),
 (4505, 0.0),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.0816496580927726),
 (4501, 0.0),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.0),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.0),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.0),
 (4491, 0.0),
 (4490, 0.06085806194501846),
 (4489, 0.0),
 (4488, 0.0),
 (4487, 0.0),
 (4486, 0.0),
 (4485, 0.0),
 (4484, 0.044280744277004756),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.0),
 (4476, 0.0),
 (4475, 0.0),
 (4474, 0.0),
 (4473, 0.0),
 (4472, 0.06262242910851494),
 (4471, 0.0),
 (4470, 0.0),
 (4469, 0.0),
 (4468, 0.06262242910851494),
 (4467, 0.0),
 (4466, 0.0),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.06900655593423542),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.0),
 (4459, 0.0),
 (4458, 0.0),
 (4457, 0.0),
 (4456, 0.0),
 (4455, 0.0),
 (4454, 0.0),
 (4453, 0.043033148291193514),
 (4452, 0.0),
 (4451, 0.0),
 (4450, 0.0),
 (4449, 0.0),
 (4448, 0.0),
 (4447, 0.0),
 (4446, 0.0),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.0),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.0),
 (4436, 0.0),
 (4435, 0.0),
 (4434, 0.0),
 (4433, 0.0),
 (4432, 0.0),
 (4431, 0.0),
 (4430, 0.0),
 (4429, 0.0),
 (4428, 0.0),
 (4427, 0.0),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.0),
 (4422, 0.0),
 (4421, 0.0),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.0),
 (4414, 0.0),
 (4413, 0.0),
 (4412, 0.07453559924999299),
 (4411, 0.0),
 (4410, 0.0),
 (4409, 0.0),
 (4408, 0.0),
 (4407, 0.0),
 (4406, 0.0),
 (4405, 0.2581988897471611),
 (4404, 0.0),
 (4403, 0.0),
 (4402, 0.0),
 (4401, 0.0),
 (4400, 0.0),
 (4399, 0.07532435771547094),
 (4398, 0.0),
 (4397, 0.0),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.0),
 (4393, 0.0),
 (4392, 0.0),
 (4391, 0.0),
 (4390, 0.0),
 (4389, 0.0),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.0),
 (4383, 0.0),
 (4382, 0.0),
 (4381, 0.0),
 (4380, 0.046373889576016826),
 (4379, 0.0),
 (4378, 0.0),
 (4377, 0.0),
 (4376, 0.0),
 (4375, 0.0),
 (4374, 0.0),
 (4373, 0.0),
 (4372, 0.0),
 (4371, 0.0),
 (4370, 0.0),
 (4369, 0.0),
 (4368, 0.0),
 (4367, 0.0),
 (4366, 0.0),
 (4365, 0.0),
 (4364, 0.0),
 (4363, 0.0),
 (4362, 0.0),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.0),
 (4358, 0.0),
 (4357, 0.06454972243679027),
 (4356, 0.0),
 (4355, 0.10540925533894598),
 (4354, 0.0),
 (4353, 0.0),
 (4352, 0.0),
 (4351, 0.06900655593423542),
 (4350, 0.0),
 (4349, 0.0),
 (4348, 0.0),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.0),
 (4343, 0.0),
 (4342, 0.0),
 (4341, 0.053838190205816545),
 (4340, 0.0),
 (4339, 0.0),
 (4338, 0.0),
 (4337, 0.0),
 (4336, 0.0),
 (4335, 0.0),
 (4334, 0.0),
 (4333, 0.0),
 (4332, 0.06666666666666665),
 (4331, 0.0),
 (4330, 0.06262242910851494),
 (4329, 0.0),
 (4328, 0.0),
 (4327, 0.04714045207910316),
 (4326, 0.0),
 (4325, 0.0),
 (4324, 0.0),
 (4323, 0.0),
 (4322, 0.0),
 (4321, 0.0),
 (4320, 0.051639777949432225),
 (4319, 0.026919095102908273),
 (4318, 0.0),
 (4317, 0.04188539082916955),
 (4316, 0.06262242910851494),
 (4315, 0.0),
 (4314, 0.0),
 (4313, 0.0),
 (4312, 0.0),
 (4311, 0.0),
 (4310, 0.0),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.06454972243679027),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.0),
 (4301, 0.0),
 (4300, 0.0),
 (4299, 0.0),
 (4298, 0.0),
 (4297, 0.0),
 (4296, 0.0),
 (4295, 0.0),
 (4294, 0.0),
 (4293, 0.0),
 (4292, 0.05270462766947299),
 (4291, 0.0),
 (4290, 0.0),
 (4289, 0.0),
 (4288, 0.0),
 (4287, 0.0),
 (4286, 0.0),
 (4285, 0.0),
 (4284, 0.0),
 (4283, 0.0),
 (4282, 0.0),
 (4281, 0.08606629658238703),
 (4280, 0.0),
 (4279, 0.0),
 (4278, 0.0),
 (4277, 0.029617443887954613),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.0),
 (4270, 0.0),
 (4269, 0.0),
 (4268, 0.0),
 (4267, 0.0),
 (4266, 0.04188539082916955),
 (4265, 0.0),
 (4264, 0.0),
 (4263, 0.04364357804719847),
 (4262, 0.0),
 (4261, 0.0408248290463863),
 (4260, 0.0),
 (4259, 0.0),
 (4258, 0.0),
 (4257, 0.0),
 (4256, 0.0),
 (4255, 0.0),
 (4254, 0.0),
 (4253, 0.0),
 (4252, 0.0),
 (4251, 0.0),
 (4250, 0.0),
 (4249, 0.0),
 (4248, 0.0),
 (4247, 0.0),
 (4246, 0.0),
 (4245, 0.0),
 (4244, 0.0),
 (4243, 0.0),
 (4242, 0.0),
 (4241, 0.0),
 (4240, 0.0),
 (4239, 0.0),
 (4238, 0.0),
 (4237, 0.0),
 (4236, 0.0),
 (4235, 0.0),
 (4234, 0.0),
 (4233, 0.03892494720807615),
 (4232, 0.0),
 (4231, 0.0),
 (4230, 0.0),
 (4229, 0.0),
 (4228, 0.0),
 (4227, 0.0),
 (4226, 0.0),
 (4225, 0.0),
 (4224, 0.0),
 (4223, 0.02418254167033372),
 (4222, 0.0),
 (4221, 0.0),
 (4220, 0.0),
 (4219, 0.0),
 (4218, 0.05773502691896257),
 (4217, 0.0),
 (4216, 0.0),
 (4215, 0.0),
 (4214, 0.06666666666666665),
 (4213, 0.0),
 (4212, 0.0),
 (4211, 0.0),
 (4210, 0.0),
 (4209, 0.0),
 (4208, 0.0),
 (4207, 0.0),
 (4206, 0.0),
 (4205, 0.0),
 (4204, 0.0),
 (4203, 0.0),
 (4202, 0.0),
 (4201, 0.0),
 (4200, 0.0),
 (4199, 0.0),
 (4198, 0.0),
 (4197, 0.0),
 (4196, 0.06666666666666665),
 (4195, 0.0),
 (4194, 0.05504818825631802),
 (4193, 0.0),
 (4192, 0.04714045207910316),
 (4191, 0.0),
 (4190, 0.1333333333333333),
 (4189, 0.0),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.0),
 (4185, 0.0),
 (4184, 0.0),
 (4183, 0.0),
 (4182, 0.0),
 (4181, 0.0),
 (4180, 0.0),
 (4179, 0.0761386987626881),
 (4178, 0.0),
 (4177, 0.0),
 (4176, 0.0),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.0),
 (4169, 0.0),
 (4168, 0.0),
 (4167, 0.03227486121839514),
 (4166, 0.0),
 (4165, 0.0),
 (4164, 0.0),
 (4163, 0.0),
 (4162, 0.0),
 (4161, 0.0),
 (4160, 0.0),
 (4159, 0.0),
 (4158, 0.03849001794597505),
 (4157, 0.0),
 (4156, 0.0),
 (4155, 0.0),
 (4154, 0.0),
 (4153, 0.0),
 (4152, 0.0),
 (4151, 0.0),
 (4150, 0.0),
 (4149, 0.021744269101781406),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.051639777949432225),
 (4145, 0.0),
 (4144, 0.0),
 (4143, 0.0),
 (4142, 0.0),
 (4141, 0.0),
 (4140, 0.0),
 (4139, 0.0),
 (4138, 0.0),
 (4137, 0.0),
 (4136, 0.0),
 (4135, 0.0),
 (4134, 0.0),
 (4133, 0.0),
 (4132, 0.0),
 (4131, 0.0),
 (4130, 0.0),
 (4129, 0.0),
 (4128, 0.0),
 (4127, 0.0),
 (4126, 0.0),
 (4125, 0.0),
 (4124, 0.0),
 (4123, 0.049690399499995326),
 (4122, 0.0),
 (4121, 0.04032389192727559),
 (4120, 0.0),
 (4119, 0.0),
 (4118, 0.033614632272640714),
 (4117, 0.0),
 (4116, 0.0),
 (4115, 0.0),
 (4114, 0.0),
 (4113, 0.0),
 (4112, 0.0),
 (4111, 0.0),
 (4110, 0.050636968354183326),
 (4109, 0.0),
 (4108, 0.0),
 (4107, 0.0),
 (4106, 0.0),
 (4105, 0.0),
 (4104, 0.0),
 (4103, 0.0),
 (4102, 0.0),
 (4101, 0.0),
 (4100, 0.0),
 (4099, 0.0),
 (4098, 0.0),
 (4097, 0.0),
 (4096, 0.0),
 (4095, 0.0),
 (4094, 0.0),
 (4093, 0.0),
 (4092, 0.0),
 (4091, 0.0),
 (4090, 0.0),
 (4089, 0.0),
 (4088, 0.0),
 (4087, 0.0),
 (4086, 0.0),
 (4085, 0.0),
 (4084, 0.0),
 (4083, 0.0),
 (4082, 0.046373889576016826),
 (4081, 0.0),
 (4080, 0.0),
 (4079, 0.0),
 (4078, 0.046373889576016826),
 (4077, 0.0),
 (4076, 0.0),
 (4075, 0.03892494720807615),
 (4074, 0.0),
 (4073, 0.0),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.0),
 (4068, 0.0),
 (4067, 0.0),
 (4066, 0.0),
 (4065, 0.04032389192727559),
 (4064, 0.0),
 (4063, 0.0),
 (4062, 0.0),
 (4061, 0.039374961547907886),
 (4060, 0.0),
 (4059, 0.06666666666666665),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.0),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.0),
 (4052, 0.0),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.03580574370197164),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.13801311186847084),
 (4045, 0.0),
 (4044, 0.0),
 (4043, 0.053838190205816545),
 (4042, 0.06666666666666665),
 (4041, 0.0),
 (4040, 0.0),
 (4039, 0.0),
 (4038, 0.0),
 (4037, 0.0),
 (4036, 0.0),
 (4035, 0.0),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.0),
 (4030, 0.0),
 (4029, 0.0),
 (4028, 0.0),
 (4027, 0.0),
 (4026, 0.0),
 (4025, 0.0),
 (4024, 0.0),
 (4023, 0.0),
 (4022, 0.0),
 (4021, 0.0),
 (4020, 0.0),
 (4019, 0.0),
 (4018, 0.0),
 (4017, 0.029814239699997188),
 (4016, 0.06454972243679027),
 (4015, 0.0),
 (4014, 0.0),
 (4013, 0.0),
 (4012, 0.0),
 (4011, 0.03984095364447979),
 (4010, 0.0),
 (4009, 0.0),
 (4008, 0.1556997888323046),
 (4007, 0.0),
 (4006, 0.0),
 (4005, 0.0),
 (4004, 0.0),
 (4003, 0.0),
 (4002, 0.0),
 (4001, 0.0),
 (4000, 0.0),
 (3999, 0.0),
 (3998, 0.0),
 (3997, 0.1126872339638022),
 (3996, 0.0),
 (3995, 0.0),
 (3994, 0.0),
 (3993, 0.0),
 (3992, 0.0),
 (3991, 0.0),
 (3990, 0.0),
 (3989, 0.0),
 (3988, 0.0),
 (3987, 0.0),
 (3986, 0.0),
 (3985, 0.0),
 (3984, 0.0),
 (3983, 0.0),
 (3982, 0.0),
 (3981, 0.0),
 (3980, 0.0),
 (3979, 0.0),
 (3978, 0.0),
 (3977, 0.0),
 (3976, 0.0778498944161523),
 (3975, 0.04879500364742665),
 (3974, 0.06085806194501846),
 (3973, 0.0),
 (3972, 0.0),
 (3971, 0.0),
 (3970, 0.06900655593423542),
 (3969, 0.0),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.059234887775909226),
 (3965, 0.0),
 (3964, 0.0),
 (3963, 0.0),
 (3962, 0.0),
 (3961, 0.0),
 (3960, 0.0),
 (3959, 0.0),
 (3958, 0.0),
 (3957, 0.0),
 (3956, 0.0),
 (3955, 0.0),
 (3954, 0.0),
 (3953, 0.0),
 (3952, 0.059234887775909226),
 (3951, 0.0),
 (3950, 0.0),
 (3949, 0.024618298195866545),
 (3948, 0.039374961547907886),
 (3947, 0.07453559924999299),
 (3946, 0.03202563076101743),
 (3945, 0.04134491152973615),
 (3944, 0.0),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.0),
 (3938, 0.0),
 (3937, 0.0),
 (3936, 0.0),
 (3935, 0.050636968354183326),
 (3934, 0.0),
 (3933, 0.0),
 (3932, 0.0),
 (3931, 0.0),
 (3930, 0.0),
 (3929, 0.0),
 (3928, 0.0),
 (3927, 0.0),
 (3926, 0.0),
 (3925, 0.0),
 (3924, 0.050636968354183326),
 (3923, 0.0),
 (3922, 0.0),
 (3921, 0.0),
 (3920, 0.0),
 (3919, 0.0),
 (3918, 0.0),
 (3917, 0.0),
 (3916, 0.06454972243679027),
 (3915, 0.0),
 (3914, 0.0),
 (3913, 0.0),
 (3912, 0.07453559924999299),
 (3911, 0.0),
 (3910, 0.0),
 (3909, 0.0),
 (3908, 0.04564354645876383),
 (3907, 0.0),
 (3906, 0.0),
 (3905, 0.0),
 (3904, 0.0),
 (3903, 0.0),
 (3902, 0.0),
 (3901, 0.0),
 (3900, 0.0),
 (3899, 0.0),
 (3898, 0.0),
 (3897, 0.0),
 (3896, 0.0),
 (3895, 0.0),
 (3894, 0.0),
 (3893, 0.0),
 (3892, 0.0),
 (3891, 0.0),
 (3890, 0.0),
 (3889, 0.0),
 (3888, 0.0),
 (3887, 0.0),
 (3886, 0.09128709291752767),
 (3885, 0.0),
 (3884, 0.0),
 (3883, 0.0),
 (3882, 0.0),
 (3881, 0.0),
 (3880, 0.0),
 (3879, 0.0),
 (3878, 0.0),
 (3877, 0.047946330148538406),
 (3876, 0.0),
 (3875, 0.0),
 (3874, 0.0),
 (3873, 0.0),
 (3872, 0.0),
 (3871, 0.0),
 (3870, 0.0),
 (3869, 0.0),
 (3868, 0.0),
 (3867, 0.0),
 (3866, 0.0),
 (3865, 0.0),
 (3864, 0.0),
 (3863, 0.0),
 (3862, 0.0),
 (3861, 0.06085806194501846),
 (3860, 0.033614632272640714),
 (3859, 0.0),
 (3858, 0.05504818825631802),
 (3857, 0.0),
 (3856, 0.0),
 (3855, 0.05504818825631802),
 (3854, 0.0),
 (3853, 0.0),
 (3852, 0.08606629658238703),
 (3851, 0.0),
 (3850, 0.0),
 (3849, 0.0),
 (3848, 0.0),
 (3847, 0.0),
 (3846, 0.04714045207910316),
 (3845, 0.0),
 (3844, 0.0),
 (3843, 0.0),
 (3842, 0.0),
 (3841, 0.0),
 (3840, 0.06666666666666665),
 (3839, 0.0),
 (3838, 0.0),
 (3837, 0.12171612389003691),
 (3836, 0.0),
 (3835, 0.0),
 (3834, 0.04364357804719847),
 (3833, 0.0),
 (3832, 0.0),
 (3831, 0.0),
 (3830, 0.0),
 (3829, 0.0),
 (3828, 0.0),
 (3827, 0.0),
 (3826, 0.0),
 (3825, 0.0),
 (3824, 0.0),
 (3823, 0.0),
 (3822, 0.0),
 (3821, 0.0),
 (3820, 0.03984095364447979),
 (3819, 0.0),
 (3818, 0.0),
 (3817, 0.0),
 (3816, 0.0),
 (3815, 0.0),
 (3814, 0.0),
 (3813, 0.0),
 (3812, 0.0),
 (3811, 0.0),
 (3810, 0.0),
 (3809, 0.0),
 (3808, 0.07595545253127499),
 (3807, 0.0),
 (3806, 0.0),
 ...]

In [202]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key= lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [204]:
recommend('Batman Begins')

The Dark Knight Rises
Raising Helen
The Dark Knight
Synecdoche, New York
Batman Forever

In [198]:
#new_df[new_df['title'] == movie].index[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [205]:
import pickle

In [207]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [208]:
pickle.dump(similarity,open('similarity.pkl','wb'))